export interface PlanningIntention {
  category: string;
  subCategories: string[];
}

export const PLANNING_INTENTIONS: PlanningIntention[] = [
  {
    category: 'New Development / New Buildings',
    subCategories: [
      'Single private dwelling',
      'One-off house (rural)',
      'Infill urban dwelling',
      'Replacement dwelling',
      'Housing estate',
      'Apartment buildings',
      'Student accommodation',
      'Build-to-Rent scheme',
      'Single-storey extension',
      'Two-storey extension',
      'Rear extension',
      'Side extension',
      'Granny flat / annex',
      'Garden room',
      'Home office',
      'Workshop / shed',
      'Detached garage',
      'Carport',
      'Raze dwelling, rebuild new',
      'Demolish ancillary structures',
      'Office building',
      'Retail unit',
      'Shopping centre',
      'Supermarket',
      'Hotel',
      'Pub / restaurant',
      'Medical centre',
      'Gym / fitness centre',
      'Warehouse / distribution',
      'Data centre',
      'Factory / production facility',
      'Logistics depot',
      'School',
      'Creche / childcare',
      'GP surgery / clinic',
      'Sports hall / clubhouse',
      'Community centre',
      'Library',
      'Holiday homes',
      'Glamping site',
      'Campsite',
      'Eco-cabins',
      'Guesthouse',
    ],
  },
  {
    category: 'Extensions / Alterations to Existing Buildings',
    subCategories: [
      'Dormer',
      'Velux / rooflight',
      'New windows / alterations',
      'Raising roof height',
      'Converting flat roof to pitched',
      'Attic conversion needing planning',
      'Garage conversion',
      'Barn or shed conversion',
      'Internal reconfiguration requiring permission',
      'Shopfront changes',
      'New signage',
      'Roller shutters',
      'External insulation (street-side)',
      'Solar PV exceeding exempted limits',
      'Heat pump external unit in restricted areas',
      'Biomass boiler flue',
      'Ramps',
      'External staircases',
      'Lifts',
    ],
  },
  {
    category: 'Change of Use',
    subCategories: [
      'Dwelling to short-term lets',
      'Dwelling to childcare facility',
      'Dwelling to medical practice',
      'Dwelling to office',
      'Dwelling to shop',
      'Shop -> cafe',
      'Shop -> takeaway',
      'Shop -> off-licence',
      'Shop -> gym',
      'Shop -> salon / barber',
      'Shop -> creche',
      'Shop -> medical clinic',
      'Shop -> offices',
      'Office -> residential',
      'Pub -> restaurant',
      'Restaurant -> takeaway',
      'Retail -> warehouse',
      'Factory -> storage',
      'Storage -> manufacturing',
      'Warehouse -> data centre',
      'Barn -> dwelling',
      'Farm shed -> commercial unit',
      'Agricultural land -> residential use',
      'Agricultural land -> equestrian centre',
      'Open space -> car park',
      'Car park -> building development',
      'Field -> sports pitch',
      'Field -> holiday accommodation (pods, glamping)',
    ],
  },
  {
    category: 'Site Works & Infrastructure',
    subCategories: [
      'New vehicular entrance',
      'Widening an entrance',
      'Relocating a gate',
      'New boundary wall',
      'Raising boundary height',
      'New driveway',
      'Paving front garden',
      'Removing a front wall',
      'New parking spaces',
      'New septic tank',
      'Upgrading wastewater treatment',
      'Soakaways / drainage changes',
      'Connection to mains services',
      'Significant excavations',
      'Retaining walls',
      'Site levelling',
      'Ground contour changes',
      'New internal estate roads',
      'Road realignment',
      'Junction upgrades',
    ],
  },
  {
    category: 'Commercial & Business Development',
    subCategories: [
      'New commercial premises',
      'Extension to commercial unit',
      'Warehousing expansion',
      'Loading bays',
      'External storage',
      'Fuel stations',
      'Car sales forecourt',
      'Vehicle repair garages',
      'Car washes / valeting',
      'Recycling or waste facility',
      'Telecommunications infrastructure',
      'Data centre expansion',
    ],
  },
  {
    category: 'Agricultural & Rural Development',
    subCategories: [
      'New farm sheds',
      'Milking parlour',
      'Slatted shed',
      'Grain store',
      'Machinery shed',
      'Silage pit',
      'Polytunnels (large)',
      'Stables',
      'Arenas',
      'Horse walker',
      'Forest road',
      'Logging yard',
      'Farm dwelling for family / succession',
      'Conversion of agricultural building to residential',
    ],
  },
  {
    category: 'Environmental & Utility Infrastructure',
    subCategories: [
      'Wind turbines',
      'Solar farms',
      'Battery storage facilities',
      'Electricity substations',
      'Water treatment facilities',
      'Telecom masts',
      'Renewable energy installations',
      'Gas pipelines',
      'District heating systems',
    ],
  },
  {
    category: 'Demolition',
    subCategories: [
      'Full demolition of dwelling',
      'Demolition in Architectural Conservation Area',
      'Demolition of protected structure',
      'Demolition of commercial premises',
      'Partial demolition with major impact',
    ],
  },
  {
    category: 'Protected Structures & Heritage',
    subCategories: [
      'Alterations to protected structures',
      'Extension to protected structure',
      'Change of use involving protected structure',
      'Works in an Architectural Conservation Area',
      'Windows/doors replacement requiring approval',
      'Shopfront changes in heritage zones',
      'Boundary or garden works affecting heritage character',
    ],
  },
  {
    category: 'Temporary Uses / Events',
    subCategories: [
      'Temporary car park',
      'Temporary school units',
      'Construction compound',
      'Festival or large event site',
      'Temporary signage',
      'Temporary structures longer than exempt periods',
    ],
  },
  {
    category: 'Special or Unusual Cases',
    subCategories: [
      'Retention of dwelling works',
      'Retention of commercial works',
      'Retention of signage',
      'Retention of extensions',
      'Shopfront signage',
      'Digital billboard',
      'Hoarding',
      'Flagpoles',
      'Slipways',
      'Pontoons',
      'Boathouses',
      'Heliports',
      'Drone hubs',
      'Bus depots',
    ],
  },
];

export const getPlanningSubCategories = (category: string): string[] => {
  const intention = PLANNING_INTENTIONS.find((i) => i.category === category);
  return intention ? intention.subCategories : [];
};

export const getAllPlanningCategories = (): string[] =>
  PLANNING_INTENTIONS.map((i) => i.category);
